@include('libs/focus-visible.min.js');
@include('libs/wow.min.js');
@include('libs/inputmask.min.js');
@include('functions/mask.js');
@include('functions/wow-init.js');
@include('functions/header.js');
@include('functions/spollers.js');
@include('functions/tabs.js');
@include('functions/politics.js');